type AutoGenerated struct {
	Name string `json:"name"`
	DisplayName string `json:"displayName"`
	Description string `json:"description"`
	Version string `json:"version"`
	Engines struct {
		Vscode string `json:"vscode"`
	} `json:"engines"`
	Categories []string `json:"categories"`
	ActivationEvents []string `json:"activationEvents"`
	Main string `json:"main"`
	Contributes struct {
		Commands []struct {
			Command string `json:"command"`
			Title string `json:"title"`
			Category string `json:"category,omitempty"`
		} `json:"commands"`
		Menus struct {
			ExplorerContext []struct {
				Command string `json:"command,omitempty"`
				When string `json:"when"`
				Group string `json:"group"`
				Submenu string `json:"submenu,omitempty"`
			} `json:"explorer/context"`
			GolangCodeHelperSubmenuGenerate []struct {
				Command string `json:"command"`
				Group string `json:"group"`
			} `json:"golangCodeHelper/submenu/generate"`
		} `json:"menus"`
		Submenus []struct {
			ID string `json:"id"`
			Label string `json:"label"`
		} `json:"submenus"`
	} `json:"contributes"`
	Scripts struct {
		VscodePrepublish string `json:"vscode:prepublish"`
		Compile string `json:"compile"`
		Watch string `json:"watch"`
		Package string `json:"package"`
		CompileTests string `json:"compile-tests"`
		WatchTests string `json:"watch-tests"`
		Pretest string `json:"pretest"`
		Lint string `json:"lint"`
		Test string `json:"test"`
	} `json:"scripts"`
	DevDependencies struct {
		TypesVscode string `json:"@types/vscode"`
		TypesGlob string `json:"@types/glob"`
		TypesMocha string `json:"@types/mocha"`
		TypesNode string `json:"@types/node"`
		TypescriptEslintEslintPlugin string `json:"@typescript-eslint/eslint-plugin"`
		TypescriptEslintParser string `json:"@typescript-eslint/parser"`
		Eslint string `json:"eslint"`
		Glob string `json:"glob"`
		Mocha string `json:"mocha"`
		Typescript string `json:"typescript"`
		TsLoader string `json:"ts-loader"`
		Webpack string `json:"webpack"`
		WebpackCli string `json:"webpack-cli"`
		VscodeTestElectron string `json:"@vscode/test-electron"`
	} `json:"devDependencies"`
}